[package]
name = "kovi-plugin-60s"
version = "0.1.0"
edition = "2024"

[dependencies]
kovi = "0.12.5"
reqwest = { version = "0.12.24", features = ["default", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"